# Generated by Django 4.2.5 on 2023-09-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracket",
            name="loser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loser",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="bracket",
            name="team_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_a",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="bracket",
            name="team_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_b",
                to="teams.team",
            ),
        ),
        migrations.AlterField(
            model_name="bracket",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to="teams.team",
            ),
        ),
    ]
