# Generated by Django 4.2.5 on 2023-09-08 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournaments", "0001_initial"),
        ("platforms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="platforms.platform"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(
                related_name="tournaments",
                through="tournaments.TournamentTeam",
                to="teams.team",
            ),
        ),
    ]
