# Generated by Django 4.2.4 on 2023-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(default="some-slug-id", max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
