# Generated by Django 4.2.6 on 2023-10-09 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="user",
        ),
    ]
