# Generated by Django 4.2.4 on 2023-09-05 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_rename_rejected_at_teaminvite_declined_at"),
        ("tournaments", "0002_alter_tournamentteam_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(
                related_name="tournaments",
                through="tournaments.TournamentTeam",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tournamentteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
        ),
    ]
