# Generated by Django 4.2.5 on 2023-09-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentregistration",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
