# Generated by Django 4.2.6 on 2023-10-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tier",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
