# Generated by Django 4.2.4 on 2023-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_game_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="prize_pool",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
