# Generated by Django 4.2.6 on 2023-10-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
        ("tournaments", "0003_remove_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(to="teams.team"),
        ),
    ]
