# Generated by Django 4.2.4 on 2023-08-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_alter_tournament_prize_pool"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="prize_pool",
            new_name="potential_prize_pool",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="entry_fee",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
