# Generated by Django 4.2.6 on 2023-10-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_alter_tier_name_alter_tournament_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="platform",
            field=models.CharField(
                choices=[
                    ("pc", "Pc"),
                    ("ps4", "Ps4"),
                    ("xbox", "Xbox"),
                    ("mobile", "Mobile"),
                ],
                default="pc",
                max_length=50,
            ),
        ),
    ]
