# Generated by Django 4.2.5 on 2023-09-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_leagueoflegendstournamentprovider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tier",
            field=models.CharField(
                choices=[
                    ("IRON", "Iron"),
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                    ("DIAMOND", "Diamond"),
                    ("MASTER", "Master"),
                    ("GRANDMASTER", "Grandmaster"),
                    ("CHALLENGER", "Challenger"),
                ],
                default="IRON",
                max_length=20,
            ),
        ),
    ]
