# Generated by Django 4.2.5 on 2023-09-20 11:33

from django.db import migrations, models
import django.db.models.deletion
import tournaments.models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_tournament_tier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="tier",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="team_size",
            field=models.IntegerField(
                default=1, validators=[tournaments.models.Tournament.validate_team_size]
            ),
        ),
        migrations.CreateModel(
            name="LeagueOfLegendsTournament",
            fields=[
                (
                    "tournament_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("IRON", "Iron"),
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                            ("DIAMOND", "Diamond"),
                            ("MASTER", "Master"),
                            ("GRANDMASTER", "Grandmaster"),
                            ("CHALLENGER", "Challenger"),
                        ],
                        default="IRON",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.leagueoflegendstournamentprovider",
                    ),
                ),
            ],
            bases=("tournaments.tournament",),
        ),
        migrations.AlterField(
            model_name="leagueoflegendstournamentcode",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.leagueoflegendstournament",
            ),
        ),
        migrations.DeleteModel(
            name="LeagueOfLegendsTournamentMetadata",
        ),
    ]
