# Generated by Django 4.2.4 on 2023-09-04 11:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_rename_rejected_at_teaminvite_declined_at"),
        ("tournaments", "0005_tournamentregistration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="potential_prize_pool",
            new_name="prize_pool",
        ),
        migrations.AddField(
            model_name="tournament",
            name="is_entry_free",
            field=models.BooleanField(default=False, help_text="No entry fee"),
        ),
        migrations.AddField(
            model_name="tournament",
            name="is_prize_pool_fixed",
            field=models.BooleanField(default=True, help_text="Fixed prize pool"),
        ),
        migrations.CreateModel(
            name="TournamentTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
    ]
