# Generated by Django 4.2.4 on 2023-09-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_gameaccountriot"),
        (
            "tournaments",
            "0006_rename_potential_prize_pool_tournament_prize_pool_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="games.game"
            ),
        ),
        migrations.DeleteModel(
            name="Game",
        ),
    ]
