# Generated by Django 4.2.5 on 2023-10-01 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "tournaments",
            "0006_remove_tournament_tier_alter_tournament_team_size_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="leagueoflegendstournament",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tournaments.leagueoflegendstournamentprovider",
            ),
        ),
    ]
