# Generated by Django 4.2.5 on 2023-10-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0007_alter_leagueoflegendstournament_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leagueoflegendstournament",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tournaments.leagueoflegendstournamentprovider",
            ),
        ),
    ]
