# Generated by Django 4.2.7 on 2023-12-28 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("IRON", "Iron"),
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                            ("EMERALD", "Emerald"),
                            ("DIAMOND", "Diamond"),
                            ("MASTER", "Master"),
                            ("GRANDMASTER", "Grandmaster"),
                            ("CHALLENGER", "Challenger"),
                        ],
                        default="SILVER",
                        max_length=50,
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "Ii"),
                            ("III", "Iii"),
                            ("IV", "Iv"),
                        ],
                        default="I",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["tier", "rank"],
            },
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "code",
                    models.CharField(
                        editable=False, max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeagueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("IRON", "Iron"),
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                            ("EMERALD", "Emerald"),
                            ("DIAMOND", "Diamond"),
                            ("MASTER", "Master"),
                            ("GRANDMASTER", "Grandmaster"),
                            ("CHALLENGER", "Challenger"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "Ii"),
                            ("III", "Iii"),
                            ("IV", "Iv"),
                        ],
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tier", "rank"],
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("BR", "Br"),
                            ("EUNE", "Eune"),
                            ("EUW", "Euw"),
                            ("JP", "Jp"),
                            ("KR", "Kr"),
                            ("LAN", "Lan"),
                            ("LAS", "Las"),
                            ("NA", "Na"),
                            ("OCE", "Oce"),
                            ("TR", "Tr"),
                            ("RU", "Ru"),
                        ],
                        default="BR",
                        max_length=10,
                    ),
                ),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=500)),
                ("token_type", models.CharField(max_length=50)),
                ("refresh_token", models.CharField(max_length=500)),
                ("id_token", models.CharField(max_length=500)),
                ("sub_id", models.CharField(max_length=500)),
                ("access_token", models.CharField(max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Summoner",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("puuid", models.CharField(max_length=255)),
                ("account_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
