# Generated by Django 4.2.7 on 2023-12-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
        ("games", "0001_initial"),
        ("leagueoflegends", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "tournament_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tournaments.tournament",
                    ),
                ),
                ("riot_id", models.IntegerField(blank=True, null=True)),
                (
                    "pick",
                    models.CharField(
                        choices=[
                            ("BLIND_PICK", "Blind Pick"),
                            ("DRAFT_MODE", "Draft Mode"),
                            ("ALL_RANDOM", "All Random"),
                            ("TOURNAMENT_DRAFT", "Tournament Draft"),
                        ],
                        default="BLIND_PICK",
                        max_length=50,
                    ),
                ),
                (
                    "map",
                    models.CharField(
                        choices=[
                            ("SUMMONERS_RIFT", "Summoners Rift"),
                            ("TWISTED_TREELINE", "Twisted Treeline"),
                            ("HOWLING_ABYSS", "Howling Abyss"),
                        ],
                        default="SUMMONERS_RIFT",
                        max_length=50,
                    ),
                ),
                (
                    "spectator",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("LOBBYONLY", "Lobbyonly"),
                            ("ALL", "All"),
                        ],
                        default="LOBBYONLY",
                        max_length=50,
                    ),
                ),
                (
                    "allowed_league_entries",
                    models.ManyToManyField(to="leagueoflegends.leagueentry"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="leagueoflegends.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=("tournaments.tournament",),
        ),
        migrations.AddField(
            model_name="summoner",
            name="game_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.gameid"
            ),
        ),
        migrations.AddField(
            model_name="summoner",
            name="league_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagueoflegends.leagueentry",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="game_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.gameid"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leagueentry",
            unique_together={("tier", "rank")},
        ),
        migrations.AddField(
            model_name="code",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.match"
            ),
        ),
        migrations.AddField(
            model_name="code",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="leagueoflegends.tournament",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classification",
            unique_together={("tier", "rank")},
        ),
    ]
