# Generated by Django 4.2.7 on 2023-12-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagueoflegends", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
