# Generated by Django 4.2.7 on 2024-01-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagueoflegends", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Classification",
        ),
        migrations.AddField(
            model_name="tournament",
            name="riot_tournament_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
