# Generated by Django 5.0.2 on 2024-02-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gameid_alter_leagueoflegendssummoner_game_id'),
        ('leagueoflegends', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gameid'),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gameid'),
        ),
    ]
