# Generated by Django 4.2.7 on 2023-12-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leagueoflegends", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="access_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="session",
            name="id_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="session",
            name="refresh_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="session",
            name="scope",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="session",
            name="sub_id",
            field=models.TextField(),
        ),
    ]
