# Generated by Django 4.2.7 on 2023-12-24 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leagueoflegends", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="summoner",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leagueentry",
            unique_together={("tier", "rank")},
        ),
        migrations.AddField(
            model_name="code",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.match"
            ),
        ),
        migrations.AddField(
            model_name="code",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="leagueoflegends.tournament",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classification",
            unique_together={("tier", "rank")},
        ),
    ]
