# Generated by Django 4.2.7 on 2023-12-24 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagueoflegends", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="classifications",
            new_name="allowed_league_entries",
        ),
    ]
