# Generated by Django 4.2.7 on 2023-12-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "leagueoflegends",
            "0004_rename_classifications_tournament_allowed_league_entries",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leagueentry",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="leagueentry",
            name="rank",
            field=models.CharField(
                choices=[("I", "I"), ("II", "Ii"), ("III", "Iii"), ("IV", "Iv")],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="leagueentry",
            name="tier",
            field=models.CharField(
                choices=[
                    ("IRON", "Iron"),
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                    ("EMERALD", "Emerald"),
                    ("DIAMOND", "Diamond"),
                    ("MASTER", "Master"),
                    ("GRANDMASTER", "Grandmaster"),
                    ("CHALLENGER", "Challenger"),
                ],
                max_length=25,
            ),
        ),
    ]
