# Generated by Django 4.2.7 on 2023-12-24 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leagueoflegends", "0005_alter_leagueentry_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leagueentry",
            unique_together={("tier", "rank")},
        ),
    ]
