# Generated by Django 4.2.7 on 2023-12-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leagueoflegends", "0006_alter_leagueentry_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summoner",
            name="revision_date",
        ),
        migrations.AlterField(
            model_name="summoner",
            name="league_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leagueoflegends.leagueentry",
            ),
        ),
    ]
