import './globals.css';
import classnames from 'classnames';
import { Nunito } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const font = Nunito({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={classnames('bg-dark text-slate-400', font.className)}>
        {children}
      </body>
    </html>
  );
}
