# Generated by Django 4.2.7 on 2023-12-30 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "activity",
                    models.CharField(
                        choices=[("team_invitation", "Team Invitation")],
                        default="team_invitation",
                        max_length=255,
                    ),
                ),
                ("data", models.JSONField()),
                ("recipient_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
