# Generated by Django 4.2.7 on 2024-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=254),
            preserve_default=False,
        ),
    ]
