# Generated by Django 4.2.6 on 2023-11-18 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_leagueoflegendsprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LeagueOfLegendsProfile",
        ),
    ]
