---
apiVersion: v1
kind: Service
metadata:
  name: hornex-postgres
  labels:
    app: hornex-postgres
spec:
  ports:
  - port: 5432
    name: sql
  clusterIP: None
  selector:
    app: hornex-postgres
