# Generated by Django 4.2.6 on 2023-11-13 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="user_id",
            new_name="recipient_id",
        ),
    ]
