# Generated by Django 4.2.7 on 2023-11-14 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_rename_user_id_notification_recipient_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5507fdbd-b5cf-45ce-be2d-9141979493d4"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
