# Generated by Django 4.2.7 on 2023-11-14 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
