# Generated by Django 4.2.4 on 2023-08-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platforms", "0001_initial"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="platform",
        ),
        migrations.AddField(
            model_name="game",
            name="platforms",
            field=models.ManyToManyField(to="platforms.platform"),
        ),
    ]
