# Generated by Django 4.2.4 on 2023-09-04 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0002_remove_game_platform_game_platforms"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameAccountRiot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("encrypted_account_id", models.CharField(max_length=30)),
                ("encrypted_puuid", models.CharField(max_length=78)),
                ("username", models.CharField(max_length=30)),
                ("region", models.CharField(choices=[("BR1", "Br1")], max_length=4)),
                ("encrypted_summoner_id", models.CharField(max_length=63)),
                ("summoner_name", models.CharField(max_length=30)),
                ("summoner_level", models.IntegerField()),
                ("revision_date", models.BigIntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
