# Generated by Django 4.2.4 on 2023-09-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_gameaccountriot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameaccountriot",
            name="region",
            field=models.CharField(
                choices=[
                    ("BR1", "Br1"),
                    ("EUN1", "Eun1"),
                    ("EUW1", "Euw1"),
                    ("JP1", "Jp1"),
                    ("KR", "Kr"),
                    ("LA1", "La1"),
                    ("LA2", "La2"),
                    ("NA1", "Na1"),
                    ("OC1", "Oc1"),
                    ("TR1", "Tr1"),
                    ("RU", "Ru"),
                    ("PH2", "Ph2"),
                    ("SG2", "Sg2"),
                    ("TH2", "Th2"),
                    ("TW2", "Tw2"),
                    ("VN2", "Vn2"),
                ],
                max_length=4,
            ),
        ),
    ]
