# Generated by Django 4.2.7 on 2023-12-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationpayment",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="tournaments.registration",
            ),
        ),
        migrations.AddField(
            model_name="pixtransaction",
            name="registration_payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pix_transactions",
                to="payments.registrationpayment",
            ),
        ),
    ]
