# Generated by Django 4.2.7 on 2023-12-28 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationpayment",
            name="registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="payments",
                to="tournaments.registration",
            ),
        ),
    ]
