# Generated by Django 4.2.7 on 2024-01-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
