// Code generated by protoc-gen-grpc-gateway-ts. DO NOT EDIT.
// source: lib/proto/hornex/match.proto

export type Match = {
  challongeMatchId: string
  id: string
  riotMatchCode: string
  round: string
  status: string
  teamA: string
  teamB: string
  tournament: string
}

export type MatchRetrieveRequest = {
  id: string
}
