# Generated by Django 4.2.6 on 2023-11-11 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0002_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(blank=True, to="teams.team"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.tournament"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.tournament"
            ),
        ),
        migrations.AddField(
            model_name="code",
            name="users",
            field=models.ManyToManyField(
                related_name="tournament_codes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bracket",
            name="loser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loser",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="bracket",
            name="team_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_a",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="bracket",
            name="team_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_b",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="bracket",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.tournament"
            ),
        ),
        migrations.AddField(
            model_name="bracket",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="leagueoflegendstournament",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tournaments.leagueoflegendstournamentprovider",
            ),
        ),
        migrations.AddField(
            model_name="leagueoflegendstournament",
            name="tiers",
            field=models.ManyToManyField(to="tournaments.tier"),
        ),
        migrations.AddField(
            model_name="code",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.leagueoflegendstournament",
            ),
        ),
    ]
