# Generated by Django 4.2.6 on 2023-11-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="cancelled_at",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="confirmed_at",
        ),
        migrations.AddField(
            model_name="registration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
