# Generated by Django 4.2.6 on 2023-10-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
        ("tournaments", "0004_alter_tournament_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(blank=True, null=True, to="teams.team"),
        ),
    ]
