# Generated by Django 4.2.6 on 2023-10-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0006_alter_tournament_teams"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="payment_date",
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("unpaid", "Unpaid"),
                    ("refunded", "Refunded"),
                    ("cancelled", "Cancelled"),
                    ("past_due", "Past Due"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
