# Generated by Django 4.2.6 on 2023-10-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0007_remove_subscription_payment_date_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
