# Generated by Django 4.2.6 on 2023-10-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0008_alter_tournament_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="feature_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
