# Generated by Django 4.2.4 on 2023-08-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_remove_game_platform_game_platforms"),
        ("platforms", "0002_alter_platform_slug"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="owner",
            new_name="created_by",
        ),
        migrations.AddField(
            model_name="team",
            name="game",
            field=models.ForeignKey(
                default="e6e2d100-2c98-449f-b0d3-ea5225905a54",
                on_delete=django.db.models.deletion.RESTRICT,
                to="games.game",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="platform",
            field=models.ForeignKey(
                default="53959a96-e5a4-479b-81ee-fa2abce936bd",
                on_delete=django.db.models.deletion.RESTRICT,
                to="platforms.platform",
            ),
            preserve_default=False,
        ),
    ]
