# Generated by Django 4.2.4 on 2023-08-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_rename_owner_team_created_by_team_game_team_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
