# Generated by Django 4.2.4 on 2023-08-31 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_alter_team_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teaminvite",
            old_name="rejected_at",
            new_name="declined_at",
        ),
    ]
