# Generated by Django 4.2.4 on 2023-09-05 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0004_rename_rejected_at_teaminvite_declined_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                through="teams.TeamMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
