# Generated by Django 4.2.6 on 2023-11-18 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_leagueoflegendsaccount_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leagueoflegendsaccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leagueoflegendsaccount",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
