# https://bun.sh/guides/ecosystem/docker

# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1 as base
WORKDIR /usr/src/app

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base
WORKDIR /usr/src/app
COPY package.json bun.lockb ./
RUN bun install

COPY . .

# run the app
# USER bun
# EXPOSE 3000/tcp
ENTRYPOINT [ "bun", "run", "dev" ]
