apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app: hornex-api
  name: hornex-api
  namespace: default
spec:
  entryPoints:
    - web

  routes:
    - match: PathPrefix(`/api`)
      kind: Rule
      services:
        - name: hornex-api
          port: 80
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: hornex-web
          port: 80
