apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hornex-api
spec:
  entryPoints:
    - web

  routes:
  - match: PathPrefix(`/api`)
    kind: Rule
    services:
    - name: hornex-api
      port: 80
