apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingressroute.yaml
labels:
- includeSelectors: true
  pairs:
    hornex.gg/service: hornex-api
