#!/usr/bin/env bash
# Create (or delete) a k3d cluster for use with Tilt
# Ref: https://docs.tilt.dev/choosing_clusters.html#k3d
# Ref: https://k3d.io/v5.6.0/
# Ref: https://github.com/k3d-io/k3d

set -Eeuo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && git rev-parse --show-toplevel)
source ${REPO_ROOT}/devops/scripts/helpers

function main() (
  case "${1}" in
    up)

      if k3d cluster list hornex &>/dev/null; then
        warning "Cluster hornex already running"
      else
        logx k3d cluster create hornex \
          --registry-create=registry:0.0.0.0:5432 \
          --port="9876:80@loadbalancer" \
          --timeout=1m
      fi

      # logx kubectl --namespace=kube-system rollout status deployment traefik --watch --timeout=5m

      # Install Traefik Resource Definitions:
      if ! kubectl get crd traefikservices.traefik.containo.us &>/dev/null; then
        logx kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
      fi


      # # # Install RBAC for Traefik:
      if ! kubectl get clusterrole traefik-ingress-controller &>/dev/null; then
        logx kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.10/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
      fi
      ;;

    down)
      logx k3d cluster delete hornex
      ;;

    *)
      error "Unknown command: '${1}', expected either 'up' or 'down'"
      ;;
  esac
)

function logx() (
  set -x
  $@
)

main "${@}"
