// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const InsertUser = `-- name: InsertUser :one
INSERT INTO users (
  first_name,
  last_name,
  email,
  birth_date,
  password
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, created_at, updated_at
`

type InsertUserParams struct {
	FirstName string
	LastName  string
	Email     string
	BirthDate pgtype.Date
	Password  string
}

type InsertUserRow struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, InsertUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.BirthDate,
		arg.Password,
	)
	var i InsertUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const SelectUserByEmail = `-- name: SelectUserByEmail :one
SELECT id, email, password, first_name, last_name, birth_date, email_confirmed, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) SelectUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRow(ctx, SelectUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const SelectUserById = `-- name: SelectUserById :one
SELECT id, email, password, first_name, last_name, birth_date, email_confirmed, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) SelectUserById(ctx context.Context, id uuid.UUID) (Users, error) {
	row := q.db.QueryRow(ctx, SelectUserById, id)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const UpdateUserById = `-- name: UpdateUserById :one
UPDATE users SET
  email = $1,
  first_name = $2,
  last_name = $3,
  birth_date = $4,
  email_confirmed = $5,
  updated_at = NOW()
WHERE id = $6
RETURNING id, email, first_name, last_name, birth_date, email_confirmed, created_at, updated_at
`

type UpdateUserByIdParams struct {
	Email          string
	FirstName      string
	LastName       string
	BirthDate      pgtype.Date
	EmailConfirmed bool
	ID             uuid.UUID
}

type UpdateUserByIdRow struct {
	ID             uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	BirthDate      pgtype.Date
	EmailConfirmed bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

func (q *Queries) UpdateUserById(ctx context.Context, arg UpdateUserByIdParams) (UpdateUserByIdRow, error) {
	row := q.db.QueryRow(ctx, UpdateUserById,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.EmailConfirmed,
		arg.ID,
	)
	var i UpdateUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.EmailConfirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
