# Generated by Django 5.0.2 on 2024-02-23 16:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_gameid_email_alter_gameid_nickname_alter_gameid_user"),
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="user",
        ),
        migrations.AddField(
            model_name="member",
            name="game_id",
            field=models.ForeignKey(
                default=uuid.uuid4(),
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.gameid",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams", through="teams.Member", to="accounts.gameid"
            ),
        ),
    ]
