# Generated by Django 4.2.7 on 2024-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
