# Generated by Django 5.0.2 on 2024-02-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="challonge_participant_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
