# Generated by Django 5.0.2 on 2024-03-01 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_team_challonge_participant_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="challonge_participant_id",
        ),
    ]
