# Generated by Django 4.2.7 on 2024-01-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_alter_team_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="deactivated_at",
            new_name="deleted_at",
        ),
        migrations.AlterField(
            model_name="team",
            name="platform",
            field=models.CharField(choices=[("pc", "Pc")], default="pc", max_length=50),
        ),
    ]
