# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: match.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bmatch.proto\x12\x06hornex"\x9b\x01\n\x05Match\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\t\x12\x12\n\ntournament\x18\x03 \x01(\t\x12\x0e\n\x06team_a\x18\x04 \x01(\t\x12\x0e\n\x06team_b\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x1a\n\x12\x63hallonge_match_id\x18\x07 \x01(\t\x12\x17\n\x0friot_match_code\x18\x08 \x01(\t""\n\x14MatchRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\t2I\n\x0cMatchService\x12\x39\n\x08Retrieve\x12\x1c.hornex.MatchRetrieveRequest\x1a\r.hornex.Match"\x00\x42\x12Z\x10hornex.gg/hornexb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "match_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\020hornex.gg/hornex"
    _globals["_MATCH"]._serialized_start = 24
    _globals["_MATCH"]._serialized_end = 179
    _globals["_MATCHRETRIEVEREQUEST"]._serialized_start = 181
    _globals["_MATCHRETRIEVEREQUEST"]._serialized_end = 215
    _globals["_MATCHSERVICE"]._serialized_start = 217
    _globals["_MATCHSERVICE"]._serialized_end = 290
# @@protoc_insertion_point(module_scope)
