# Generated by Django 4.2.4 on 2023-08-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platforms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="slug",
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
