import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { WindowIcon } from '@heroicons/react/24/outline';
import { Badge } from '@/components/ui/badge';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-14 max-w-screen-2xl items-center">
            <div>Hornex</div>
            <div className="flex flex-1 items-center justify-between space-x-2 md:justify-end">
              <nav className="flex items-center">
                <a href="" className="text-sm">
                  Logout
                </a>
              </nav>
            </div>
          </div>
        </header>
        <div className="flex w-full px-8">
          <div className="min-w-[180px] min-h-[100vh] self-start border-r border-border/40 mt-4">
            <div className="pb-12 flex items-center">
              <a href="" className="text-lg">
                Hornex
              </a>
              <Badge className="ml-2" variant="outline">
                v0.0.1
              </Badge>
            </div>
            <ul className="text-sm font-semibold">
              <li>
                <a href="/tournaments">
                  <div className="flex items-center">
                    <WindowIcon className="w-4 h-4 mr-2" />
                    Tournaments
                  </div>
                </a>
              </li>
            </ul>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
