# Generated by Django 4.2.6 on 2023-10-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="game",
            field=models.CharField(
                choices=[("league-of-legends", "League Of Legends")],
                default="league-of-legends",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="platform",
            field=models.CharField(
                choices=[
                    ("pc", "Pc"),
                    ("ps4", "Ps4"),
                    ("xbox", "Xbox"),
                    ("mobile", "Mobile"),
                ],
                default="pc",
                max_length=50,
            ),
        ),
    ]
