// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: lol_account.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const InsertAccount = `-- name: InsertAccount :one
INSERT INTO lol_accounts (
  id,
  user_id,
  account_id,
  puuid,
  summoner_name,
  summoner_level,
  profile_icon_id,
  revision_date
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
RETURNING id, user_id, account_id, puuid, summoner_name, summoner_level, profile_icon_id, revision_date, verified, created_at, updated_at
`

type InsertAccountParams struct {
	ID            string
	UserID        uuid.UUID
	AccountID     string
	Puuid         string
	SummonerName  string
	SummonerLevel int32
	ProfileIconID int32
	RevisionDate  int64
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (LolAccounts, error) {
	row := q.db.QueryRow(ctx, InsertAccount,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.Puuid,
		arg.SummonerName,
		arg.SummonerLevel,
		arg.ProfileIconID,
		arg.RevisionDate,
	)
	var i LolAccounts
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Puuid,
		&i.SummonerName,
		&i.SummonerLevel,
		&i.ProfileIconID,
		&i.RevisionDate,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
