// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailsConfirmationCode struct {
	ID               uuid.UUID
	Email            string
	ConfirmationCode string
	CreatedAt        pgtype.Timestamp
}

type Teams struct {
	ID        uuid.UUID
	Name      string
	CreatedBy uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Users struct {
	ID             uuid.UUID
	Email          string
	Password       string
	FirstName      string
	LastName       string
	BirthDate      pgtype.Date
	EmailConfirmed pgtype.Bool
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}
