# Generated by Django 4.2.6 on 2023-11-11 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("slug", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameAccountRiot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("encrypted_summoner_id", models.CharField(max_length=63)),
                ("encrypted_account_id", models.CharField(max_length=30)),
                ("encrypted_puuid", models.CharField(max_length=78)),
                ("username", models.CharField(max_length=30)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("BR1", "Br1"),
                            ("EUN1", "Eun1"),
                            ("EUW1", "Euw1"),
                            ("JP1", "Jp1"),
                            ("KR", "Kr"),
                            ("LA1", "La1"),
                            ("LA2", "La2"),
                            ("NA1", "Na1"),
                            ("OC1", "Oc1"),
                            ("TR1", "Tr1"),
                            ("RU", "Ru"),
                            ("PH2", "Ph2"),
                            ("SG2", "Sg2"),
                            ("TH2", "Th2"),
                            ("TW2", "Tw2"),
                            ("VN2", "Vn2"),
                        ],
                        max_length=4,
                    ),
                ),
                ("summoner_name", models.CharField(max_length=30)),
                ("summoner_level", models.IntegerField()),
                ("revision_date", models.BigIntegerField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
