apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hornex-api
  name: hornex-api
spec:
  template:
    spec:
      containers:
      - name: hornex-api
        command:
        - /src/dev-api.sh
