apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/services/hornex-api
- pvc.yaml
patches:
- path: deployment-command.yaml
- path: deployment-env.yaml
- path: deployment-storage.yaml
