import z from 'zod';

export const tournament = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  published: z.boolean(),
  status: z.string(),
  start_date: z.string(),
  registration_start_date: z.date(),
  registration_end_date: z.date(),
  check_in_duration: z.number(),
  end_date: z.string(),
  start_time: z.string(),
  end_time: z.string(),
  is_entry_free: z.boolean(),
  is_prize_pool_fixed: z.boolean(),
  prize_pool: z.number(),
  entry_fee: z.number(),
  max_teams: z.number(),
  team_size: z.number(),
  created_at: z.string(),
  updated_at: z.string(),
  organizer: z.string(),
  game: z.string(),
  platform: z.string(),
  teams: z.array(z.string()),
  classifications: z.string().array(),
  feature_image: z.string(),
  open_classification: z.boolean(),
  challonge_tournament_url: z.string(),
});
export type Tournament = z.infer<typeof tournament>;
