# Generated by Django 4.2.7 on 2024-02-07 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="check_in_opens_at",
        ),
    ]
