# Generated by Django 4.2.7 on 2023-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bracket",
            old_name="round",
            new_name="phase",
        ),
        migrations.RemoveField(
            model_name="bracket",
            name="loser",
        ),
        migrations.RemoveField(
            model_name="bracket",
            name="team_a",
        ),
        migrations.RemoveField(
            model_name="bracket",
            name="team_b",
        ),
        migrations.RemoveField(
            model_name="bracket",
            name="winner",
        ),
        migrations.AddField(
            model_name="bracket",
            name="loser_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bracket",
            name="team_a_id",
            field=models.UUIDField(default="d32f7280-a1d0-4a32-85ed-5332a350bec0"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bracket",
            name="team_b_id",
            field=models.UUIDField(default="d32f7280-a1d0-4a32-85ed-5332a350bec0"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bracket",
            name="winner_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="tournaments", to="teams.team"
            ),
        ),
    ]
