# Generated by Django 5.0.2 on 2024-02-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="currency",
            field=models.CharField(
                choices=[("USD", "Usd"), ("BRL", "Brl"), ("EUR", "Eur")],
                default="BRL",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="phase",
            field=models.CharField(
                choices=[
                    ("registration_open", "Registration Open"),
                    ("check_in", "Check In"),
                    ("in_progress", "In Progress"),
                    ("finished", "Finished"),
                ],
                default="registration_open",
                max_length=50,
            ),
        ),
    ]
