# Generated by Django 5.0.2 on 2024-02-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="challonge_match_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
