# Generated by Django 5.0.2 on 2024-03-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="losses",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rank",
            name="wins",
            field=models.IntegerField(default=0),
        ),
    ]
