# Generated by Django 5.0.2 on 2024-02-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
