# Generated by Django 4.2.7 on 2024-01-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="challonge_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="challonge_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tournament",
            name="feature_image",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
