# Generated by Django 4.2.7 on 2023-12-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="classification_open",
            field=models.BooleanField(default=False),
        ),
    ]
