# Generated by Django 4.2.7 on 2023-12-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
        ("tournaments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="tournaments", to="teams.team"
            ),
        ),
    ]
