# Generated by Django 4.2.7 on 2024-01-15 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_alter_team_description"),
        (
            "tournaments",
            "0003_tournament_challonge_id_tournament_challonge_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
    ]
