# Generated by Django 5.0.2 on 2024-03-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_rank_losses_rank_wins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
