# Generated by Django 5.0.2 on 2024-02-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_tournament_checked_in_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="checked_in_at",
        ),
        migrations.AddField(
            model_name="tournament",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
    ]
