# Generated by Django 5.0.2 on 2024-02-20 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_tournament_currency_alter_tournament_phase"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="phase",
            new_name="status",
        ),
    ]
