# Generated by Django 4.2.7 on 2023-12-26 01:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_tournament_classification_open"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="classification_open",
            new_name="is_classification_open",
        ),
    ]
