# Generated by Django 4.2.7 on 2023-12-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_alter_tournament_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tier",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
