# Generated by Django 4.2.7 on 2023-11-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
        (
            "tournaments",
            "0003_rename_round_bracket_phase_remove_bracket_loser_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(related_name="tournaments", to="teams.team"),
        ),
    ]
