# Generated by Django 4.2.7 on 2023-12-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_alter_tournament_entry_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="entry_fee",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="prize_pool",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
