# Generated by Django 5.0.2 on 2024-02-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0003_match_challonge_match_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("ongoing", "Ongoing"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=50,
            ),
        ),
    ]
