# Generated by Django 4.2.7 on 2024-01-15 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tournaments", "0004_checkin"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="user",
            field=models.ForeignKey(
                default="38d3a7cc-1de8-4f1f-9617-9fa4b39b6d25",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
