# Generated by Django 5.0.2 on 2024-02-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_alter_match_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="metadata",
            field=models.JSONField(default={}),
        ),
    ]
