# Generated by Django 4.2.7 on 2023-11-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_alter_tournament_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="bracket",
            name="phase",
        ),
        migrations.AddField(
            model_name="bracket",
            name="round",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.round",
            ),
            preserve_default=False,
        ),
    ]
