# Generated by Django 5.0.2 on 2024-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_participant_team_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="email",
            field=models.EmailField(default="user@hornex.gg", max_length=254),
            preserve_default=False,
        ),
    ]
