# Generated by Django 4.2.7 on 2024-02-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_leagueoflegendsello_leagueoflegendsprovider_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="team_a_id",
            new_name="team1_id",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="team_b_id",
            new_name="team2_id",
        ),
        migrations.AddField(
            model_name="match",
            name="challonge_match_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="team1_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("pending", "Pending"),
                    ("ongoing", "Ongoing"),
                    ("finished", "Finished"),
                ],
                default="all",
                max_length=50,
            ),
        ),
    ]
