# Generated by Django 4.2.7 on 2023-12-21 18:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_leagueoflegendsaccount_tier"),
        ("tournaments", "0004_alter_tier_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("IRON", "Iron"),
                            ("BRONZE", "Bronze"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                            ("EMERALD", "Emerald"),
                            ("DIAMOND", "Diamond"),
                            ("MASTER", "Master"),
                            ("GRANDMASTER", "Grandmaster"),
                            ("CHALLENGER", "Challenger"),
                        ],
                        default="SILVER",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("I", "I"),
                            ("II", "Ii"),
                            ("III", "Iii"),
                            ("IV", "Iv"),
                        ],
                        default="I",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="leagueoflegendstournament",
            name="tiers",
        ),
        migrations.DeleteModel(
            name="Tier",
        ),
        migrations.AddField(
            model_name="leagueoflegendstournament",
            name="classifications",
            field=models.ManyToManyField(to="tournaments.classification"),
        ),
    ]
