# Generated by Django 5.0.2 on 2024-03-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_alter_tournament_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="riot_match_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
