# Generated by Django 5.0.2 on 2024-02-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0004_rename_phase_tournament_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("registration_open", "Registration Open"),
                    ("check_in", "Check In"),
                    ("in_progress", "In Progress"),
                    ("finished", "Finished"),
                ],
                default="registration_open",
                max_length=50,
            ),
        ),
    ]
