# Generated by Django 5.0.2 on 2024-02-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_rename_leagueoflegendsello_leagueoflegendsleague_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueoflegendsleague',
            name='queue_type',
        ),
    ]
