# Generated by Django 5.0.2 on 2024-03-13 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_match_riot_match_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="riot_match_id",
            new_name="riot_match_code",
        ),
    ]
