# Generated by Django 5.0.2 on 2024-02-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_alter_tournament_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="registration_end_date",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("announced", "Announced"),
                    ("registering", "Registering"),
                    ("running", "Running"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="announced",
                max_length=50,
            ),
        ),
    ]
