# Generated by Django 4.2.7 on 2024-01-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_checkin_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="check_in_closes_at",
            field=models.DateTimeField(default="2024-01-19 22:02:44.715291"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="check_in_opens_at",
            field=models.DateTimeField(default="2024-01-19 22:02:44.715291"),
            preserve_default=False,
        ),
    ]
