# Generated by Django 5.0.2 on 2024-02-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_participant_email"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participant",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="nickname",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
