# Generated by Django 5.0.2 on 2024-02-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_match_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
