# Generated by Django 4.2.7 on 2023-11-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_round_remove_bracket_phase_bracket_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="tournament",
            field=models.ForeignKey(
                default="d32f7280-a1d0-4a32-85ed-5332a350bec0",
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.tournament",
            ),
            preserve_default=False,
        ),
    ]
