# Generated by Django 4.2.7 on 2023-12-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_classification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="rank",
            field=models.CharField(
                choices=[("I", "I"), ("II", "Ii"), ("III", "Iii"), ("IV", "Iv")],
                default="I",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="tier",
            field=models.CharField(
                choices=[
                    ("IRON", "Iron"),
                    ("BRONZE", "Bronze"),
                    ("SILVER", "Silver"),
                    ("GOLD", "Gold"),
                    ("PLATINUM", "Platinum"),
                    ("EMERALD", "Emerald"),
                    ("DIAMOND", "Diamond"),
                    ("MASTER", "Master"),
                    ("GRANDMASTER", "Grandmaster"),
                    ("CHALLENGER", "Challenger"),
                ],
                default="SILVER",
                max_length=50,
            ),
        ),
    ]
