# Generated by Django 5.0.2 on 2024-02-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0006_alter_participant_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="tournaments.tournament",
            ),
        ),
    ]
