# Generated by Django 4.2.7 on 2023-11-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0006_round_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rounds",
                to="tournaments.tournament",
            ),
        ),
    ]
