# Generated by Django 4.2.7 on 2024-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0006_tournament_check_in_closes_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="check_in_closes_at",
        ),
        migrations.AddField(
            model_name="tournament",
            name="check_in_duration",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="check_in_opens_at",
            field=models.DateTimeField(null=True),
        ),
    ]
