# Generated by Django 5.0.2 on 2024-02-11 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0006_remove_leagueoflegendsleague_queue_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leagueoflegendstournament",
            old_name="allowed_ellos",
            new_name="classifications",
        ),
    ]
