# Generated by Django 5.0.2 on 2024-03-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0006_rename_riot_match_id_match_riot_match_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="challonge_participant_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
