# Generated by Django 5.0.2 on 2024-02-29 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0006_alter_match_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="challonge_participant_id",
        ),
    ]
