# Generated by Django 5.0.2 on 2024-02-13 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0007_rename_allowed_ellos_leagueoflegendstournament_classifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_prize_pool_fixed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("place", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("custom", models.BooleanField(default=False)),
                ("content", models.TextField(default="")),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tournaments.tournament"
                    ),
                ),
            ],
        ),
    ]
