# Generated by Django 4.2.7 on 2023-11-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0007_alter_round_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracket",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brackets",
                to="tournaments.round",
            ),
        ),
    ]
