# Generated by Django 5.0.2 on 2024-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0007_alter_registration_challonge_participant_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leagueoflegendstournament",
            name="provider",
        ),
        migrations.AddField(
            model_name="leagueoflegendstournament",
            name="riot_provider_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="region",
            field=models.CharField(
                choices=[
                    ("BR", "Br"),
                    ("EUNE", "Eune"),
                    ("EUW", "Euw"),
                    ("JP", "Jp"),
                    ("KR", "Kr"),
                    ("LAN", "Lan"),
                    ("LAS", "Las"),
                    ("NA", "Na"),
                    ("OCE", "Oce"),
                    ("TR", "Tr"),
                    ("RU", "Ru"),
                ],
                default="BR",
                max_length=10,
            ),
        ),
    ]
