# Generated by Django 5.0.2 on 2024-03-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_registration_challonge_participant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='status',
            new_name='state',
        ),
    ]
