# Generated by Django 5.0.2 on 2024-03-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0007_remove_registration_challonge_participant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="challonge_participant_id",
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
