# Generated by Django 5.0.2 on 2024-03-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0004_remove_team_challonge_participant_id"),
        ("tournaments", "0008_registration_challonge_participant_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="loser_id",
        ),
        migrations.RemoveField(
            model_name="match",
            name="team_a_id",
        ),
        migrations.RemoveField(
            model_name="match",
            name="team_b_id",
        ),
        migrations.RemoveField(
            model_name="match",
            name="winner_id",
        ),
        migrations.AddField(
            model_name="match",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="loser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loser",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team_a",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_a",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_b",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winner",
                to="teams.team",
            ),
        ),
    ]
