# Generated by Django 4.2.7 on 2024-01-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0008_alter_tournament_check_in_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="platform",
            field=models.CharField(choices=[("pc", "Pc")], default="pc", max_length=50),
        ),
    ]
