# Generated by Django 5.0.2 on 2024-02-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0008_tournament_is_prize_pool_fixed_prize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="is_prize_pool_fixed",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="prize_pool",
        ),
        migrations.AddField(
            model_name="tournament",
            name="prize_pool_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
