# Generated by Django 5.0.2 on 2024-02-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_remove_tournament_is_prize_pool_fixed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='custom',
            new_name='is_money',
        ),
        migrations.AlterField(
            model_name='prize',
            name='amount',
            field=models.FloatField(),
        ),
    ]
