# Generated by Django 5.0.2 on 2024-03-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0009_remove_match_loser_id_remove_match_team_a_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="round",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
