# Generated by Django 4.2.7 on 2023-11-25 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0009_key_alter_round_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="round",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="round",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
