# Generated by Django 5.0.2 on 2024-03-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0010_match_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="rules",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="match",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("underway", "Underway"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=50,
            ),
        ),
    ]
