# Generated by Django 4.2.7 on 2023-11-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0010_alter_round_options_round_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="status",
        ),
        migrations.AddField(
            model_name="tournament",
            name="phase",
            field=models.CharField(
                choices=[
                    ("registration_open", "Registration Open"),
                    ("results_tracking", "Results Tracking"),
                    ("payment_pending", "Payment Pending"),
                    ("finished_and_paid", "Finished And Paid"),
                ],
                default="registration_open",
                max_length=50,
            ),
        ),
    ]
