# Generated by Django 4.2.7 on 2023-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0011_remove_tournament_status_tournament_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="registration_end_date",
            field=models.DateTimeField(default="2023-10-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="registration_start_date",
            field=models.DateTimeField(default="2023-10-1"),
            preserve_default=False,
        ),
    ]
