# Generated by Django 5.0.2 on 2024-03-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0011_match_rules_alter_match_metadata_alter_match_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="rules",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="checked_in",
        ),
        migrations.AddField(
            model_name="tournament",
            name="about",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
    ]
