# Generated by Django 5.0.2 on 2024-03-01 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0012_remove_match_rules_remove_tournament_checked_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("not_started", "Not Started"),
                    ("underway", "Underway"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_started",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.tournament",
            ),
        ),
    ]
