# Generated by Django 4.2.7 on 2023-11-27 14:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0012_tournament_registration_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("team_a_id", models.UUIDField()),
                ("team_b_id", models.UUIDField()),
                ("winner_id", models.UUIDField(blank=True, null=True)),
                ("loser_id", models.UUIDField(blank=True, null=True)),
                ("is_wo", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("future", "Future"),
                            ("past", "Past"),
                            ("live", "Live"),
                        ],
                        default="future",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.round",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("team_a_id", models.UUIDField()),
                ("team_b_id", models.UUIDField()),
                ("team_a_score", models.CharField(max_length=255)),
                ("team_b_score", models.CharField(max_length=255)),
                ("schedule", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.match",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Bracket",
        ),
    ]
