# Generated by Django 5.0.2 on 2024-03-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0013_alter_match_status_alter_match_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="team_a_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="team_b_score",
            field=models.IntegerField(default=0),
        ),
    ]
