# Generated by Django 4.2.7 on 2023-11-29 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
        ("tournaments", "0013_match_matchround_delete_bracket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="code",
            name="users",
        ),
        migrations.AddField(
            model_name="code",
            name="match",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.match",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leagueoflegendstournament",
            name="map",
            field=models.CharField(
                choices=[
                    ("SUMMONERS_RIFT", "Summoners Rift"),
                    ("TWISTED_TREELINE", "Twisted Treeline"),
                    ("HOWLING_ABYSS", "Howling Abyss"),
                ],
                default="SUMMONERS_RIFT",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="leagueoflegendstournament",
            name="pick",
            field=models.CharField(
                choices=[
                    ("BLIND_PICK", "Blind Pick"),
                    ("DRAFT_MODE", "Draft Mode"),
                    ("ALL_RANDOM", "All Random"),
                    ("TOURNAMENT_DRAFT", "Tournament Draft"),
                ],
                default="BLIND_PICK",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="leagueoflegendstournament",
            name="riot_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leagueoflegendstournament",
            name="spectator",
            field=models.CharField(
                choices=[("NONE", "None"), ("LOBBYONLY", "Lobbyonly"), ("ALL", "All")],
                default="LOBBYONLY",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tournaments", to="teams.team"
            ),
        ),
    ]
