# Generated by Django 4.2.7 on 2023-11-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_initial"),
        ("tournaments", "0013_match_matchround_delete_bracket"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueoflegendstournamentprovider",
            name="provider_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="tournaments", to="teams.team"
            ),
        ),
    ]
