# Generated by Django 5.0.2 on 2024-03-02 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0014_match_team_a_score_match_team_b_score"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["-created_at"]},
        ),
    ]
