# Generated by Django 5.0.2 on 2024-03-02 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0015_alter_match_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["updated_at"]},
        ),
    ]
