# Generated by Django 5.0.2 on 2024-03-02 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0016_alter_match_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["created_at"]},
        ),
    ]
