# Generated by Django 5.0.2 on 2024-03-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0017_alter_match_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="current_round",
            field=models.IntegerField(default=0),
        ),
    ]
