# Generated by Django 5.0.2 on 2024-03-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0018_match_current_round"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="current_round",
        ),
        migrations.AddField(
            model_name="tournament",
            name="current_round",
            field=models.IntegerField(default=0),
        ),
    ]
