# Generated by Django 5.0.2 on 2024-03-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0019_remove_match_current_round_tournament_current_round"),
    ]

    operations = [
        migrations.RenameField(
            model_name="match",
            old_name="finished_at",
            new_name="ended_at",
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("not_started", "Not Started"),
                    ("underway", "Underway"),
                    ("ended", "Ended"),
                    ("cancelled", "Cancelled"),
                ],
                default="not_started",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("announced", "Announced"),
                    ("registering", "Registering"),
                    ("running", "Running"),
                    ("ended", "Ended"),
                    ("cancelled", "Cancelled"),
                ],
                default="announced",
                max_length=50,
            ),
        ),
    ]
