# Generated by Django 5.0.2 on 2024-03-02 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0020_rename_finished_at_match_ended_at_alter_match_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="tournaments.tournament",
            ),
        ),
    ]
