# Generated by Django 5.0.2 on 2024-03-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0021_alter_registration_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
