import "./globals.css";
import classnames from "classnames";
import {
  Fira_Code,
  Roboto_Condensed,
  Oswald,
  Fira_Sans,
  Heebo,
} from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fira_code = Fira_Code({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

const roboto_condensed = Roboto_Condensed({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

const owswald = Oswald({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

const fira = Heebo({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={classnames("bg-dark  text-slate-400", fira_code.className)}
      >
        {children}
      </body>
    </html>
  );
}
