# Generated by Django 4.2.7 on 2023-12-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
