# Generated by Django 5.0.2 on 2024-04-09 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameID",
        ),
    ]
