name: deploy

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: services/hornex-api

    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/deploy.sh
        env:
          AWS_PEM_FILE: ${{ secrets.AWS_PEM_FILE }}
          AWS_EC2_HOSTNAME: ${{ vars.AWS_EC2_HOSTNAME }}
