name: hornex-api

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: hornex
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: hornex
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      rabbitmq:
        image: rabbitmq:3-management
        env:
          RABBITMQ_DEFAULT_USER: hornex
          RABBITMQ_DEFAULT_PASS: hornex
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5672:5672

    defaults:
      run:
        working-directory: services/hornex-api

    steps:
      - uses: actions/checkout@v4

      - run: pip install poetry

      - uses: actions/setup-python@v5
        with:
          python-version-file: services/hornex-api/pyproject.toml
          cache: poetry

      - run: poetry install

      - run: poetry run python manage.py migrate
        env:
          HORNEX_SQL_ENGINE: django.db.backends.postgresql
          HORNEX_SQL_DATABASE: hornex
          HORNEX_SQL_USER: postgres
          HORNEX_SQL_PASSWORD: hornex
          HORNEX_SQL_HOST: localhost
          HORNEX_SQL_PORT: 5432

          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: hornex
          RABBITMQ_PASSWORD: hornex

      - run: poetry run python manage.py test
        env:
          EFI_CLIENT_ID: your_test_efi_client_id
          EFI_CLIENT_SECRET: your_test_efi_client_secret
          EFI_BASE_URL: https://test.pix-h.api.efipay.com.br
          EFI_AUTHORIZED_IPS: 127.0.0.1, localhost
          EFI_PIX_KEY: your_test_pix_key
          EFI_PIX_EXPIRATION: 3600
          EFI_HMAC_SECRET_MESSAGE: your_test_hornex
          EFI_HMAC_SECRET_KEY: your_test_hornex_api_hmac_secret_gg

          RIOT_RSO_CLIENT_ID: your_test_riot_rso_client_id
          RIOT_RSO_CLIENT_SECRET: your_test_riot_rso_client_secret
          RIOT_RSO_PROVIDER_URL: https://test.auth.riotgames.com
          RIOT_API_KEY: your_test_riot_api_key
          DJANGO_ALLOWED_HOSTS: localhost, 127.0.0.1, your_test_ngrok_app_domain

          APP_URL: https://your_test_ngrok_app_domain

          HORNEX_SQL_ENGINE: django.db.backends.postgresql
          HORNEX_SQL_HOST: localhost
          HORNEX_SQL_DATABASE: hornex
          HORNEX_SQL_USER: postgres
          HORNEX_SQL_PASSWORD: hornex

          STRIPE_API_KEY: your_test_stripe_api_key

          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: hornex
          RABBITMQ_PASSWORD: hornex

      - run: poetry run ruff check .

      - run: poetry run ruff format --check .
