# Generated by Django 4.2.7 on 2023-12-09 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeagueOfLegendsAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("puuid", models.CharField(max_length=78)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("summoner_name", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
