# Generated by Django 5.0.2 on 2024-02-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeagueOfLegendsSummoner",
            fields=[
                ("id", models.CharField(max_length=500, primary_key=True, serialize=False)),
                ("puuid", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
