# Generated by Django 5.0.2 on 2024-02-22 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gameid",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leagueoflegendssummoner",
            name="ello",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.leagueoflegendsleague",
            ),
        ),
        migrations.AddField(
            model_name="leagueoflegendssummoner",
            name="game_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.gameid"
            ),
        ),
        migrations.AddField(
            model_name="termsandconditionsagreement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="termsandconditionsagreement",
            unique_together={("user", "version")},
        ),
    ]
