# Generated by Django 4.2.7 on 2023-11-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueoflegendsaccount",
            name="puuid",
            field=models.CharField(
                default="OxC7Ddyh8gdhnc24FbEaS3UbCCvEvdneOiKpzLeBADyY_aHvkRvt8ZL0e5sfZaoLaJUN0TmmsgvuRA",
                max_length=78,
            ),
            preserve_default=False,
        ),
    ]
