# Generated by Django 5.0.2 on 2024-02-23 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gameid",
            name="email",
            field=models.EmailField(default="admin@hornex.gg", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gameid",
            name="nickname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="gameid",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
