# Generated by Django 4.2.7 on 2023-12-18 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leagueoflegendsaccount",
            name="password",
        ),
        migrations.RemoveField(
            model_name="leagueoflegendsaccount",
            name="username",
        ),
    ]
