# Generated by Django 4.2.7 on 2023-12-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_leagueoflegendsaccount_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueoflegendsaccount",
            name="account_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leagueoflegendsaccount",
            name="jti",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leagueoflegendsaccount",
            name="profile_icon_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leagueoflegendsaccount",
            name="revision_date",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leagueoflegendsaccount",
            name="sub",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leagueoflegendsaccount",
            name="summoner_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leagueoflegendsaccount",
            name="summoner_level",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leagueoflegendsaccount",
            name="tag_line",
            field=models.CharField(
                choices=[
                    ("BR1", "Br1"),
                    ("EUN1", "Eun1"),
                    ("EUW1", "Euw1"),
                    ("JP1", "Jp1"),
                    ("KR", "Kr"),
                    ("LA1", "La1"),
                    ("LA2", "La2"),
                    ("NA1", "Na1"),
                    ("OC1", "Oc1"),
                    ("TR1", "Tr1"),
                    ("RU", "Ru"),
                    ("PH2", "Ph2"),
                    ("SG2", "Sg2"),
                    ("TH2", "Th2"),
                    ("TW2", "Tw2"),
                    ("VN2", "Vn2"),
                ],
                default="BR1",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="leagueoflegendsaccount",
            name="puuid",
            field=models.CharField(max_length=255),
        ),
    ]
