# Generated by Django 4.2.7 on 2023-12-18 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_leagueoflegendsaccount_account_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leagueoflegendsaccount",
            name="region",
        ),
    ]
