# Generated by Django 5.0.2 on 2024-03-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_profile_discord_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="discord_invite_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
