# Generated by Django 4.2.7 on 2023-12-21 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_leagueoflegendsaccount_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leagueoflegendsaccount",
            name="tier",
        ),
    ]
