# Generated by Django 4.2.7 on 2023-12-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_classification_and_more"),
        ("accounts", "0007_remove_leagueoflegendsaccount_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="leagueoflegendsaccount",
            name="classification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournaments.classification",
            ),
        ),
        migrations.AlterField(
            model_name="leagueoflegendsaccount",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
